#!/usr/bin/env python3
"""Dependency-free static site generator; public content contains no credentials."""
from pathlib import Path
from html import escape
import json
import shutil
from content import HOME_INTRO, HOME_SECTIONS, FAQ, PAGES, AREAS

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist'
BASE = 'https://fencingmerseyside.co.uk'
OUT.mkdir(exist_ok=True)
shutil.copytree(ROOT / 'assets', OUT / 'assets', dirs_exist_ok=True)
E = escape

def link(slug, label, cls=''):
    return f'<a href="/{slug}/" class="{cls}">{E(label)}</a>'

def paragraphs(text):
    return ''.join('<p>'+E(p.strip())+'</p>' for p in text.split('\n\n') if p.strip())

def button(label='Tell us about your project', href='/contact/', light=False):
    return f'<a class="button{" light" if light else ""}" href="{href}">{E(label)} <span class="arrow" aria-hidden="true">↗</span></a>'

def header(slug):
    items=[('fencing-installation','Fencing'),('timber-fencing','Materials'),('areas','Our areas'),('fencing-costs','Advice')]
    nav=''.join(f'<a href="/{s}/"'+(' aria-current="page"' if s==slug else '')+f'>{l}</a>' for s,l in items)
    return f'''<a class="skip" href="#main">Skip to content</a>
    <div class="topline">Garden fencing · Gates · Repairs · Across Merseyside</div>
    <header class="header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="Fencing Merseyside home"><img src="/assets/logo.svg" width="340" height="64" alt="Fencing Merseyside"></a><button class="menu" type="button" data-menu-button aria-expanded="false" aria-controls="navigation">Menu</button><nav class="nav" id="navigation" data-navigation aria-label="Main navigation">{nav}{button('Project enquiry')}</nav></div></header>'''

def footer():
    return f'''<section class="cta" aria-labelledby="cta-title"><div class="wrap"><div><p class="eyebrow">Your garden. Your next chapter.</p><h2 id="cta-title">Let’s start with your boundary.</h2><p>Tell us where you are, what you have in mind, and what your garden needs.</p></div>{button('Make an enquiry',light=True)}</div></section>
    <footer class="footer"><div class="wrap"><div class="footer-grid"><div><div class="footer-brand">Fencing <em>Merseyside.</em></div><p>Thoughtful guidance for garden fencing, gates and repairs across Merseyside.</p><p>Planned email: hello@fencingmerseyside.co.uk<br>Email setup in progress.</p><p>Service area: Merseyside, England.</p></div><div><h3>Explore fencing</h3>{link('fencing-installation','Fencing installation')}{link('timber-fencing','Timber fencing')}{link('composite-fencing','Composite fencing')}{link('fence-repairs','Fence repairs')}{link('garden-gates','Garden gates')}</div><div><h3>Local areas</h3>{''.join(link('areas/'+a[0],a[1]) for a in AREAS)}{link('areas','All service areas')}</div><div><h3>Useful information</h3>{link('fencing-costs','Fencing cost guide')}{link('boundary-guide','Boundaries & planning')}{link('about','About the website')}{link('contact','Project enquiry')}{link('sitemap','HTML sitemap')}</div></div><div class="footer-bottom"><span>© 2026 Fencing Merseyside. Design images are illustrative.</span><div>{link('privacy','Privacy')}{link('accessibility','Accessibility')}<a href="/sitemap.xml">XML sitemap</a></div></div></div></footer>'''

def breadcrumbs(slug, label):
    middle='<a href="/areas/">Areas</a> <span aria-hidden="true">/</span> ' if slug.startswith('areas/') else ''
    return f'<div class="wrap breadcrumb"><nav aria-label="Breadcrumb"><a href="/">Home</a> <span aria-hidden="true">/</span> {middle}<span aria-current="page">{E(label)}</span></nav></div>'

def write(slug, title, description, body, label=None, schema=None, noindex=False):
    url=BASE+('/'+slug+'/' if slug else '/')
    structured=[{'@context':'https://schema.org','@type':'WebSite','name':'Fencing Merseyside','url':BASE+'/','inLanguage':'en-GB'}]
    if slug:
        structured.append({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},{'@type':'ListItem','position':2,'name':label or title,'item':url}]})
    if schema: structured.append(schema)
    ld=json.dumps(structured,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')
    page=f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{E(title)}</title><meta name="description" content="{E(description,quote=True)}"><meta name="robots" content="{'noindex, follow' if noindex else 'index, follow'}"><link rel="canonical" href="{url}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="alternate icon" href="/assets/favicon.ico"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><meta name="theme-color" content="#183a2c"><meta property="og:type" content="website"><meta property="og:site_name" content="Fencing Merseyside"><meta property="og:title" content="{E(title,quote=True)}"><meta property="og:description" content="{E(description,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}/assets/social.jpg"><meta property="og:image:alt" content="Illustrative timber fencing in a planted English garden"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">{ld}</script><script src="/assets/site.js" defer></script>{'<link rel="preload" as="image" href="/assets/garden-fence.webp" fetchpriority="high">' if not slug else ''}</head><body>{header(slug)}<main id="main">{body}</main>{footer()}</body></html>'''
    icon='<svg class="icon" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M4 16 16 4M4 4h12v12"/></svg>'
    down='<svg class="icon" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M10 3v14M4 11l6 6 6-6"/></svg>'
    page=page.replace('↗',icon).replace('↓',down)
    page=page.replace('as="image" href="/assets/garden-fence.webp" fetchpriority="high"','as="image" href="/assets/garden-fence.webp" imagesrcset="/assets/garden-fence-small.webp 768w, /assets/garden-fence.webp 1536w" imagesizes="100vw" fetchpriority="high"')
    page=page.replace('src="/assets/garden-gate.webp" width=', 'src="/assets/garden-gate.webp" srcset="/assets/garden-gate-small.webp 768w, /assets/garden-gate.webp 1536w" sizes="(max-width: 800px) 100vw, 50vw" width=')
    dest=OUT/slug/'index.html' if slug else OUT/'index.html'
    dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(page)
    return ld

def faq_html(items=FAQ):
    return '<div class="faq"><p class="eyebrow">A few helpful answers</p><h2>Before you choose your fence.</h2>'+''.join(f'<details><summary>{E(q)}</summary><p>{E(a)}</p></details>' for q,a in items)+'</div>'

def enquiry_form(prefix='enquiry'):
    return f'''<form class="enquiry-form" action="https://formsubmit.co/hello@fencingmerseyside.co.uk" method="POST" data-enquiry-form>
    <input type="hidden" name="_subject" value="New Fencing Merseyside project enquiry"><input type="hidden" name="_next" value="{BASE}/enquiry-received/"><input type="hidden" name="_template" value="table"><div class="sr-only" aria-hidden="true"><label for="{prefix}-trap">Leave this field empty</label><input id="{prefix}-trap" name="_honey" type="text" tabindex="-1" autocomplete="off"></div>
    <p class="notice">Enquiries opening soon. Email setup is in progress, so this form cannot send messages yet. Please check back before sharing your details.</p>
    <fieldset disabled><legend class="sr-only">Project enquiry — currently unavailable</legend><div class="form-grid"><label for="{prefix}-name">Your name<input id="{prefix}-name" name="name" autocomplete="name" required maxlength="100"></label><label for="{prefix}-email">Email address<input id="{prefix}-email" name="email" type="email" autocomplete="email" required maxlength="254"></label><label for="{prefix}-area">Town or postcode area<input id="{prefix}-area" name="area" autocomplete="address-level2" placeholder="For example, Crosby or L23" required maxlength="120"></label><label for="{prefix}-service">What are you planning?<select id="{prefix}-service" name="project" required><option value="">Choose your project</option><option>New garden fencing</option><option>Fence repair or replacement</option><option>Timber or closeboard fencing</option><option>Composite fencing</option><option>Garden or side gate</option><option>Advice on options</option></select></label><label class="full" for="{prefix}-details">Tell us a little about your project<textarea id="{prefix}-details" name="message" placeholder="Approximate length, existing fence, preferred style and access. Please do not include sensitive information." required maxlength="5000"></textarea></label><div class="full"><p class="form-note">Once enabled, your details will be used to respond to this enquiry. The form uses FormSubmit’s secure enquiry processor. Read our {link('privacy','privacy information')}.</p><button class="button" type="submit" disabled>Enquiries opening soon <span aria-hidden="true">↗</span></button></div></div></fieldset></form>'''

home=f'''<section class="hero" aria-labelledby="hero-title"><img class="hero-photo" src="/assets/garden-fence.webp" srcset="/assets/garden-fence-small.webp 768w, /assets/garden-fence.webp 1536w" sizes="100vw" width="1536" height="1024" fetchpriority="high" alt="Illustrative timber garden fence with a lawn, natural planting and a gravel path"><div class="wrap"><div class="hero-content"><p class="eyebrow">Fencing Merseyside · Considered outdoor spaces</p><h1 id="hero-title">Good fences.<br><em>Better gardens.</em></h1><p class="intro">{HOME_INTRO}</p><div class="actions">{button('Start your project',light=True)}<a class="button ghost" href="#fencing-options">Explore the options <span aria-hidden="true">↓</span></a></div></div></div><span class="hero-caption">AI-generated design illustration.<br>Not a completed customer project.</span></section>
<div class="rail"><div class="wrap"><div class="rail-item"><span class="rail-number">01</span>Privacy, style & everyday use</div><div class="rail-item"><span class="rail-number">02</span>Materials chosen for your space</div><div class="rail-item"><span class="rail-number">03</span>Across the five Merseyside boroughs</div></div></div>
<section class="section" id="fencing-options"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Find your fence</p><h2>A boundary with<br>a little more thought.</h2></div><p>From the warmth of timber to a well-fitted garden gate, explore the details that make a boundary feel right.</p></div><div class="cards"><article class="card"><div class="card-art"><img src="/assets/garden-fence-small.webp" width="768" height="512" loading="lazy" alt="Illustrative natural timber boundary with green planting"><span class="art-caption">Design illustration</span></div><div class="card-body"><span class="tag">01 / Natural & versatile</span><h3>Timber fencing</h3><p>Closeboard, panels and thoughtful finishing details. A natural backdrop for the garden.</p>{link('timber-fencing','Explore timber fencing ↗','text-link')}</div></article><article class="card"><div class="card-art composite" role="img" aria-label="Illustration of contemporary horizontal composite fence boards"><span class="art-caption">Material illustration</span></div><div class="card-body"><span class="tag">02 / Clean & contemporary</span><h3>Composite fencing</h3><p>Compare modern systems, colours and the practical details behind lower routine maintenance.</p>{link('composite-fencing','Explore composite fencing ↗','text-link')}</div></article><article class="card"><div class="card-art"><img src="/assets/garden-gate-small.webp" width="768" height="512" loading="lazy" alt="Illustrative timber side gate with black fittings and garden planting"><span class="art-caption">Design illustration</span></div><div class="card-body"><span class="tag">03 / The finishing touch</span><h3>Garden gates</h3><p>A considered entrance, with opening width, support and hardware planned together.</p>{link('garden-gates','Explore garden gates ↗','text-link')}</div></article></div></div></section>
<section class="section white"><div class="wrap split"><div class="split-photo"><img src="/assets/garden-gate.webp" width="1536" height="1024" loading="lazy" alt="Design illustration of a solid timber side gate beside an English garden"><span class="photo-note">AI-generated design illustration</span></div><div><p class="eyebrow">More than a line in the garden</p><h2>Built around<br>the way you live.</h2><p>A boundary can bring privacy, define a space and make room for a calmer garden. Begin with what matters to you, then consider the materials and the site.</p><ul class="checklist"><li>Screening that suits your sightlines</li><li>Posts and panels considered together</li><li>Gates that fit everyday access</li><li>A clear brief before a quotation</li></ul>{button('Tell us what you need')}</div></div></section>
<section class="section sage"><div class="wrap"><p class="eyebrow">A simple place to start</p><h2>From an idea<br>to a clearer plan.</h2><div class="steps"><div class="step"><span class="step-number">01.</span><h3>Describe your space</h3><p>Share your town, the existing boundary and what you want to improve. Approximate measurements are useful.</p></div><div class="step"><span class="step-number">02.</span><h3>Consider the options</h3><p>Compare materials, height, access and maintenance. Ground conditions and wind exposure also matter.</p></div><div class="step"><span class="step-number">03.</span><h3>Agree the details</h3><p>Confirm the specification, site conditions and written scope before accepting work or paying a deposit.</p></div></div></div></section>
<section class="section"><div class="wrap editorial"><aside><p class="eyebrow">Your fencing guide</p>{''.join(f'<a href="#{s}">{E(h)}</a>' for s,h,t in HOME_SECTIONS)}{button('Project enquiry')}</aside><div class="prose">{''.join(f'<section id="{s}"><h2>{E(h)}</h2>{paragraphs(t)}</section>' for s,h,t in HOME_SECTIONS)}<p>Keep exploring: {link('fencing-installation','installation planning')}, {link('fence-repairs','repair advice')}, {link('fencing-costs','fencing costs')} and {link('boundary-guide','boundary checks')}.</p></div></div></section>
<section class="section white"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Local spaces. Local considerations.</p><h2>Across Merseyside.</h2></div><p>Enquire about towns and neighbourhoods across all five boroughs. Every boundary starts with its own conditions.</p></div><div class="area-grid">{''.join(f'<a class="area-card" href="/areas/{a[0]}/"><strong>{a[1]}</strong><span>Local fencing guide</span><span aria-hidden="true">↗</span></a>' for a in AREAS)}</div><p>{link('areas','Explore towns and service areas ↗','text-link')}</p></div></section>
<section class="section"><div class="wrap">{faq_html()}</div></section>
<section class="section sage" id="enquire"><div class="wrap split"><div><p class="eyebrow">Let’s start a conversation</p><h2>What does your<br>garden need?</h2><p>New fencing, a repair, or a gate to complete the boundary? Tell us a little about your space.</p><p>Enquiries will open once email setup is complete.</p></div><div>{enquiry_form('home')}</div></div></section>'''
write('', 'Fencing Merseyside | Garden Fencing, Repairs & Gates', 'Explore fencing in Merseyside: timber and composite garden fences, repairs and gates. Local guides across Liverpool, Wirral, Sefton, Knowsley and St Helens.', home)

for page in PAGES:
    slug=page['slug']
    body=breadcrumbs(slug,page['label'])+f'<section class="page-hero"><div class="wrap"><p class="eyebrow">{E(page["category"])} · Fencing Merseyside</p><h1>{E(page["h1"])}</h1><p class="lede">{E(page["intro"])}</p>{button("Enquire about your project")}</div></section>'
    body+='<section class="section"><div class="wrap page-body prose">'+''.join(f'<section><h2>{E(h)}</h2>{paragraphs(p)}</section>' for h,p in page['sections'])
    if slug=='boundary-guide': body+='<p>Official guidance: <a href="https://www.planningportal.co.uk/permission/common-projects/fences-gates-and-garden-walls/planning-permission">Planning Portal: fences, gates and garden walls</a>.</p>'
    body+='<div class="related"><h3>Keep exploring</h3>'+''.join(link(s,next((p['label'] for p in PAGES if p['slug']==s),'All Merseyside areas')) for s in page['related'])+'</div></div></section>'
    body+='<section class="section sage"><div class="wrap split"><div><p class="eyebrow">Your next step</p><h2>Tell us about<br>your boundary.</h2><p>Share your town, approximate measurements and priorities. A clear brief makes the next conversation more useful.</p></div><div>'+enquiry_form(slug.replace('/','-'))+'</div></div></section>'
    write(slug,page['title'],page['description'],body,page['label'])

SPECIALS = {
 'areas': ('Merseyside Fencing Areas | Liverpool, Wirral, Sefton & More','Fencing across Merseyside.','Explore fencing guides for the five Merseyside boroughs, with towns, local planning considerations and project enquiries.', '<p>Fencing Merseyside accepts project enquiries for towns and neighbourhoods within Liverpool, Wirral, Sefton, Knowsley and St Helens. Include your location so suitability and availability can be discussed.</p>'+''.join('<h2>'+E(a[1])+'</h2><p>'+E(a[2])+'.</p><p>'+link('areas/'+a[0],'Read the '+a[1]+' fencing guide ↗')+'</p>' for a in AREAS)+'<p>These are service-area guides, not claims of local offices. Final access, measurements and site conditions need to be confirmed for each property.</p>'),
 'about': ('About Fencing Merseyside | Garden Fencing Project Guidance','A considered approach to your garden.','Learn about Fencing Merseyside and the practical information behind planning a garden fence, repair or gate project.', '<p>Fencing Merseyside is a website for garden fencing, repairs and gates across the Merseyside area. Its aim is to make the early decisions easier: what kind of boundary you need, which materials suit it and what to include in an enquiry.</p><h2>Useful detail before big promises</h2><p>Good planning means looking at the whole boundary, not simply choosing a panel. Posts, ground conditions, wind exposure, access and everyday use belong in the same conversation. The guides on this website explain these considerations in plain language.</p><h2>Clear project information</h2><p>We invite enquiries about new fencing, repairs, timber and composite options, and garden gates. Availability, the final specification, costs and terms need to be agreed for the actual project. Discuss the project scope, relevant experience and the terms of any work before making a decision.</p><h2>Images and service areas</h2><p>The garden and gate imagery is AI-generated design illustration. It shows possible styles and is not a completed-project portfolio. The website describes a Merseyside service area; it does not claim offices in each town. Verified business and project information can be added as it becomes available.</p>'),
 'contact': ('Contact Fencing Merseyside | Garden Fencing Enquiries','Let’s talk about your garden.','Enquire about garden fencing, fence repairs or a gate in Merseyside. Share your town, approximate measurements and project details.', '<p>Tell us what you have in mind, whether it is a new boundary, a damaged section or a garden gate. Include your town and the approximate length where possible. Please do not include payment information or sensitive property documents.</p><p>Planned email: hello@fencingmerseyside.co.uk (setup in progress)<br>Service area: Merseyside, England. Visits and project availability by arrangement; no walk-in office is advertised.</p>'+enquiry_form('contact')+'<h2>Helpful details to include</h2><ul><li>The town or postcode area and approximate fence length.</li><li>What is already there and whether removal is needed.</li><li>Preferred height, style and any gate requirements.</li><li>Narrow access, slopes, nearby walls or planting.</li><li>Whether boundary position and permissions have been checked.</li></ul><p>The form uses an external spam-protected processor. Submission will be enabled after the email destination is active; no particular response time is promised.</p>'),
 'privacy': ('Privacy Information | Fencing Merseyside','Your enquiry, handled with care.','How Fencing Merseyside enquiry information is used, including the external form processor, email handling and contact for privacy questions.', '<p>This information describes the website at fencingmerseyside.co.uk. Contact <a href="mailto:hello@fencingmerseyside.co.uk">hello@fencingmerseyside.co.uk</a> with privacy questions. Updated 9 October 2026.</p><h2>Information you choose to provide</h2><p>The enquiry form asks for your name, email address, town or postcode area, project type and message. Do not include payment details, identity documents or sensitive personal information. Information is used to respond to your enquiry and discuss a potential project, including steps you request before any contract.</p><h2>Form and hosting services</h2><p>Submitting the form sends the entered details to FormSubmit, an external processor that forwards submissions by email and provides spam protection. Read <a href="https://formsubmit.co/privacy.pdf">FormSubmit’s privacy information</a> before submitting. The hosting provider and form processor may also handle technical data such as IP addresses and request logs. Their services may process data outside the UK; consult their current policies for details. Email forwarding and the receiving mailbox provider handle message delivery.</p><h2>Cookies and analytics</h2><p>This website does not include advertising trackers or analytics scripts and does not set its own cookies. Following an external link or submitting the form opens another service, which may have its own cookies or anti-spam checks. The website does not store enquiry details in your browser.</p><h2>Your information and rights</h2><p>Enquiry information should be kept only for as long as needed for the enquiry and any related legal or business requirements. You may request access, correction or deletion where applicable, and raise concerns with the UK Information Commissioner’s Office. The business operator must confirm its retention arrangements and any further processing before expanding the services offered.</p>'),
 'accessibility': ('Accessibility | Fencing Merseyside','Designed to be easier to use.','Accessibility features and contact details for the Fencing Merseyside website.', '<p>The website uses semantic headings, labelled forms, keyboard-accessible navigation, visible focus styles and a skip link. The content is available as ordinary HTML, including the sitemap, rather than requiring client-side navigation.</p><h2>Use the site your way</h2><p>You can browse with a keyboard, zoom text and use a reduced-motion preference. Navigation and forms are designed for small screens as well as desktop displays. Illustrative images include alternative text or accessible descriptions where they carry meaning.</p><h2>Tell us about a difficulty</h2><p>If a page or form is difficult to use, email <a href="mailto:hello@fencingmerseyside.co.uk">hello@fencingmerseyside.co.uk</a> with the page address and a description of the issue. An external form processor may have different accessibility behaviour. No formal third-party accessibility certification is claimed.</p>'),
 'enquiry-received': ('Enquiry Submission | Fencing Merseyside','Thank you for your project enquiry.','Information after completing the Fencing Merseyside enquiry form.', '<p>You have returned from the enquiry processor. If it showed a successful submission, your enquiry has been accepted for processing. This page alone does not confirm email delivery or an appointment.</p><p>If the processor showed an error or requested a further step, complete that step or email <a href="mailto:hello@fencingmerseyside.co.uk">hello@fencingmerseyside.co.uk</a>. Keep a copy of your project details for your records.</p>'+button('Explore fencing advice','/fencing-costs/')),
}
for slug,(title,h1,desc,content) in SPECIALS.items():
    body=breadcrumbs(slug,h1)+f'<section class="page-hero"><div class="wrap"><p class="eyebrow">Fencing Merseyside</p><h1>{E(h1)}</h1></div></section><section class="section"><div class="wrap page-body prose">{content}</div></section>'
    write(slug,title,desc,body,h1,noindex=slug=='enquiry-received')

all_slugs=['']+[p['slug'] for p in PAGES]+[s for s in SPECIALS if s!='enquiry-received']+['sitemap']
map_content='<p>Every main page is linked below. Use this directory to explore fencing options, local areas and project guidance.</p><div class="map-links"><a href="/">Home — Fencing Merseyside</a>'+''.join(link(p['slug'],p['label']) for p in PAGES)+''.join(link(s,{'areas':'All service areas','about':'About','contact':'Project enquiry','privacy':'Privacy','accessibility':'Accessibility'}[s]) for s in SPECIALS if s!='enquiry-received')+'</div><p><a href="/sitemap.xml">XML sitemap for search engines</a></p>'
write('sitemap','HTML Sitemap | Fencing Merseyside','Browse every Fencing Merseyside page: garden fencing, materials, repairs, gates, Merseyside areas, advice and enquiries.',breadcrumbs('sitemap','Sitemap')+'<section class="page-hero"><div class="wrap"><p class="eyebrow">Explore the website</p><h1>All the useful details,<br>in one place.</h1></div></section><section class="section"><div class="wrap page-body prose">'+map_content+'</div></section>','Sitemap')
OUT.joinpath('sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join('<url><loc>'+BASE+('/'+s+'/' if s else '/')+'</loc></url>\n' for s in all_slugs)+'</urlset>\n')
OUT.joinpath('robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+BASE+'/sitemap.xml\n')
write('404','Page Not Found | Fencing Merseyside','Return to Fencing Merseyside to explore garden fences, repairs, gates and local guidance.','<section class="section"><div class="wrap"><p class="eyebrow">Page not found</p><h1>Let’s find the right path.</h1><p>This address does not match a page on the website.</p>'+button('Return to the homepage','/')+'</div></section>',noindex=True)
shutil.copyfile(OUT/'404'/'index.html',OUT/'404.html')
shutil.rmtree(OUT/'404')
OUT.joinpath('CNAME').write_text('fencingmerseyside.co.uk\n')
OUT.joinpath('.nojekyll').touch()
print(f'Built {len(all_slugs)} indexable pages + submission and 404 pages in {OUT}')
