HOME_INTRO = 'Thoughtful fencing for the place you call home. Explore garden boundaries, timber fencing, repairs and gates across Merseyside, then tell us what your outdoor space needs.'

HOME_SECTIONS = [
('fencing-merseyside', 'Fencing in Merseyside, made easier to plan', '''A good fence does more than mark the edge of a garden. It creates privacy, gives planting a backdrop and helps an outdoor space feel settled. Choosing fencing in Merseyside means balancing the look you want with practical questions about wind, ground conditions, access and maintenance. A sheltered courtyard in Liverpool can need a different approach from an exposed garden on the Wirral coast. The right starting point is your site, rather than a photograph of a fence that may have been built in very different conditions.

Fencing Merseyside brings the decisions together in one place. Explore the main fencing options, read practical advice and use the enquiry form to describe your project. Whether you are considering a full garden boundary, a replacement panel or a matching side gate, a clear brief makes the next conversation more useful. Include your town, approximate fence length and what you want to improve. Privacy, appearance, security and upkeep can all matter, but deciding which comes first helps narrow the choices.'''),
('choose-your-fence', 'Choose a fence that fits your garden', '''Timber remains a familiar choice for Merseyside fencing because it works with many styles of home and garden. Closeboard fencing uses overlapping vertical boards to form a solid boundary, while ready-made panels offer repeatable sections with different finishes. Decorative panels and trellis can soften the appearance of a boundary, although an open design gives less screening than a solid fence. Consider both sides of the fence, especially if the boundary faces a neighbour or a shared access route.

Composite fencing is another option where lower routine maintenance is a priority. It has its own installation requirements, including spacing, support and movement allowances, so it should be assessed as a complete system rather than a direct swap for timber boards. Concrete posts and gravel boards can be considered with compatible timber panels, particularly where keeping wood away from damp ground is important. No material is completely maintenance free, and product warranties depend on the actual manufacturer and installation conditions. Our material guides explain the questions to ask before agreeing a specification.'''),
('installation-and-repairs', 'New fencing, or a careful repair?', '''A damaged fence does not always need replacing from end to end. If one panel has failed but the surrounding posts are sound, a local repair may be worth assessing. If several posts are leaning, the timber is extensively decayed or the fence keeps moving in windy weather, replacing a larger section could be the more sensible route. Photos help describe the problem, but the condition of buried post sections and fixings usually needs a closer inspection.

When planning new fencing, think about the complete job. The quotation should explain the fence type, height, post spacing, ground preparation and how the old materials will be handled. Ask whether gates, gravel boards and any finishing treatment are included. Sloping gardens may require stepped panels or a different construction approach. Changes in level, tree roots, drains and utility routes should be discussed before any holes are dug. A tidy plan for access, material storage and protecting nearby planting is just as useful as choosing the face of the fence.'''),
('local-conditions', 'Local conditions matter across Merseyside', '''Merseyside includes Liverpool, Wirral, Sefton, Knowsley and St Helens, with a wide variety of streets, gardens and boundary layouts. Coastal exposure around parts of Wirral and Sefton can make wind loading an important design consideration. A taller solid fence can present a large surface to gusts, so post specification, fixings and foundations need to suit the site. Avoid assuming that a heavier-looking panel automatically makes the whole boundary stronger.

Older terraced streets may have narrow passages and limited room to bring materials through to the back garden. Elsewhere, longer suburban boundaries can make changes in level and consistent alignment more noticeable. Drainage and soil conditions vary from property to property, even within the same town. Tell us about restricted access, existing walls, nearby trees and any shared paths when you enquire. Our local area pages provide useful starting points for Liverpool, Wirral, Sefton, Knowsley and St Helens without treating every garden in a borough as the same.'''),
('compare-quotes', 'What to ask a fencing company in Merseyside', '''When comparing a fencing company in Merseyside with other local fencing firms, look for a quotation that explains the work in plain language. A headline figure means little if one quote includes disposal and another excludes it. Check the proposed materials, fence dimensions, post type, gate hardware and whether VAT applies. Confirm what happens if digging reveals an obstruction or the existing boundary needs additional preparation. Written details make it easier to compare the scope fairly.

Ask about relevant experience, insurance and examples of similar work, and verify any claims that matter to you. Agree payment stages and understand the terms before paying a deposit. If a guarantee is offered, ask what it covers, how long it lasts and who is responsible for putting a problem right. Manufacturer cover and workmanship cover are different things. The design images on this website are illustrations of possible styles, rather than a portfolio of completed customer projects. We do not use invented reviews or promises to help you make a decision.'''),
('cost-and-care', 'Plan the budget and the care afterwards', '''Fencing costs depend on more than the length of the boundary. Fence height, materials, post specification, site access, removal of the old fence and the condition of the ground can all affect the work involved. Gates add hardware and alignment requirements, and decorative details can change both the material list and the installation time. An accurate measurement and a few clear photographs are a better starting point than a generic price per panel. Our cost guide explains how to request an itemised quotation without suggesting that every garden should cost the same.

Once the fence is in place, routine checks can help small problems stay small. Look for loose fixings, damaged boards and movement after strong winds. Keep soil and dense vegetation away from timber where the product specification allows, and follow the manufacturer's instructions for cleaning or treatment. Avoid stacking heavy materials against panels or fixing large objects to a fence that was not designed to carry them. If you are unsure whether a leaning section is safe, keep people away from it and arrange an assessment rather than trying to straighten it under load.'''),
('start-your-project', 'A useful enquiry starts with a few details', '''You do not need a finished design to start planning your fencing project. Tell us your Merseyside town, the kind of boundary you have and what you want to achieve. If you can safely measure the approximate length, include that too. Mention whether the old fence needs removing, whether a gate is required and how materials could reach the garden. A short description of the style you like helps, but practical details make the brief more useful.

Before work is agreed, confirm ownership and the exact position of the boundary. A fence is not always proof of a legal boundary, and responsibility should not be assumed from which side the posts face. Discuss the proposal with affected neighbours and check planning requirements where relevant, especially beside a highway, around listed buildings or where local restrictions apply. Then use our project enquiry form to bring your notes together. A considered brief gives the conversation a clear starting point and helps turn a broad search for fencing firms in Merseyside into a specific plan for your property.''')
]

FAQ = [
('Which Merseyside areas can I enquire about?', 'You can enquire about projects in Liverpool, Wirral, Sefton, Knowsley and St Helens, including towns and neighbourhoods within those boroughs. Include your town and postcode area so access and the project location can be discussed. Scheduling and project suitability need to be confirmed individually.'),
('What is the difference between panels and closeboard fencing?', 'Fence panels are pre-made sections fitted between posts. Closeboard fencing uses overlapping vertical boards and can be supplied as panels or assembled on site. The construction, post specification and fixings all matter; the name alone does not tell you how a fence will perform.'),
('Can a damaged fence be repaired?', 'Sometimes. A repair can be appropriate where damage is localised and the remaining posts and fixings are sound. Widespread rot, repeated movement or several failing posts may justify replacement. A site assessment is needed before choosing the most suitable option.'),
('How much does fencing in Merseyside cost?', 'There is no reliable single price for every property. Length, height, material, post type, access, old-fence disposal, gates and ground preparation affect the quotation. Request a written, itemised quote for your actual boundary rather than relying on a headline price.'),
('Do I need planning permission for a new fence?', 'Requirements depend on height, location and restrictions affecting the property. Fences beside a highway, listed buildings and properties with conditions or local directions may need particular checks. Confirm current guidance with your local council or the Planning Portal before work starts.'),
('Are the website pictures completed local projects?', 'The garden and gate photographs are AI-generated design illustrations. They show possible styles, not completed Fencing Merseyside projects, customer properties or evidence of workmanship. Verified project photographs can be added when available.')
]

# Separate, useful pages rather than repeated keyword variations.
PAGES = [
{'slug':'fencing-installation','title':'Fencing Installation in Merseyside | Garden Boundaries','h1':'A better boundary starts with a better plan.','label':'Fencing installation','category':'Services','description':'Plan garden fencing installation in Merseyside. Compare materials, posts, access and removal requirements before requesting a project quotation.','intro':'A new fence should suit the garden it belongs to. Start with the boundary, the ground and the way you use the space, then build the specification around them.','sections':[
('Start with the whole boundary','Measure the approximate run, note any changes in level and record the height you are considering. Check the boundary position and responsibility before agreeing work. Existing fencing can help describe a project, but it does not necessarily establish the legal boundary. Where a fence is shared or faces a neighbouring property, discussing the proposal early can prevent avoidable misunderstandings.'),
('Panels, boards and supporting posts','The visible panel is only part of a fence. Posts, fixings, gravel boards and foundations need to work together. Timber posts can create a consistent natural finish, while compatible concrete posts and gravel boards are another option. Closeboard construction, decorative panels and composite systems have different requirements. An exposed site or a heavy gate needs particular attention to support and loading.'),
('Prepare for a practical installation','Tell us about narrow side passages, steps, parking restrictions and areas that need protecting. Removing an existing fence, handling waste and working around roots or underground services should be included in the project discussion. Digging should not begin until relevant services and site hazards have been assessed. Sloping ground may require stepped panels or site-built construction, with the detail agreed before materials are ordered.'),
('Request a clear scope of work','A useful quotation specifies materials, height, length, post type, gates, removal, waste arrangements and any treatment. Ask how unforeseen ground conditions will be handled and whether VAT is included where applicable. Use the enquiry form to share your town, approximate measurements and priorities. Photos can support the conversation, but final measurements and conditions should be confirmed before installation.')], 'related':['timber-fencing','fence-repairs','fencing-costs']},
{'slug':'timber-fencing','title':'Timber & Closeboard Fencing Merseyside | Material Guide','h1':'Natural timber. A considered finish.','label':'Timber fencing','category':'Materials','description':'Explore timber garden fencing in Merseyside: closeboard, overlap panels, trellis, timber posts and care advice for a well-planned boundary.','intro':'Warm, familiar and adaptable, timber fencing can complement everything from a compact courtyard to a long planted garden. The right construction matters as much as the appearance.','sections':[
('Closeboard and overlap explained','Closeboard uses overlapping vertical boards to create a solid boundary. Overlap panels typically use horizontal overlapping boards within a framed section. Both descriptions cover a range of products, so compare actual timber dimensions, rails, frames and fixings. A fence should be specified for the site rather than chosen on the product name alone.'),
('Privacy without forgetting the garden','Solid panels screen views, while trellis and more open details allow some sightlines and light through. Consider how the fence will look from your house, the neighbour’s side and nearby paths. A dark finish can make planting stand out, while untreated or appropriately treated timber can offer a softer backdrop. Finish choices should follow the supplier’s instructions and any restrictions that apply to the product.'),
('Posts and keeping timber away from damp','Timber posts, concrete posts and compatible gravel boards each affect the final appearance and maintenance. Good drainage and detailing around the base matter because prolonged damp can shorten timber’s service life. Ask what treatment the supplied timber has received and what ongoing care is recommended. Do not assume a treatment label creates an unlimited lifespan or removes the need for checks.'),
('Care through the seasons','Inspect panels and fixings after windy weather and check for damage or movement. Follow manufacturer guidance for cleaning and protective finishes, keeping plants and stored items from loading the fence. Where a board or section is damaged, arrange an assessment before it affects adjacent parts. Our enquiry form lets you describe the style, length and location of a timber fencing project without committing to an unsuitable product.')], 'related':['fencing-installation','composite-fencing','fence-repairs']},
{'slug':'composite-fencing','title':'Composite Fencing Merseyside | Options & Planning','h1':'A contemporary fence, with a clear specification.','label':'Composite fencing','category':'Materials','description':'Compare composite fencing for Merseyside gardens. Understand maintenance, support systems, expansion gaps, colours and quote requirements.','intro':'Composite fencing can offer a consistent modern finish with less routine painting than some timber options. Its suitability depends on the complete system and your site.','sections':[
('Compare the whole system','Composite boards are generally installed with compatible posts, rails or channels. Check the product specification, recommended spans and permitted fence height. Mixing components from unrelated systems can affect fit, performance and warranty terms. Ask for the manufacturer and product range in the quotation so you know exactly what is proposed.'),
('Allow for movement and exposure','Composite materials can expand and contract with temperature. Installation details should include the manufacturer’s movement allowances, drainage provisions and fastening requirements. Wind exposure still matters: a solid composite fence needs suitable posts and foundations, just as other solid fencing does. The colour and material alone do not establish strength.'),
('Maintenance is lower, not absent','Cleaning may still be needed, particularly near trees or damp shaded areas. Read the care instructions before using pressure washers, solvents or abrasive tools. Product colour can change with weathering, and guarantees may include specific limits and conditions. Ask how scratches, damaged boards and replacement parts would be handled.'),
('Make a balanced comparison','Compare the installed scope with timber, including posts, disposal, gates and any groundwork. Choose a colour and profile that works with the house and neighbouring boundaries rather than focusing only on a showroom sample. Include your approximate length, height and postcode area in the project enquiry. If you are deciding between materials, explain your priorities for appearance, care and budget.')], 'related':['timber-fencing','fencing-installation','fencing-costs']},
{'slug':'fence-repairs','title':'Fence Repairs Merseyside | Panels, Posts & Storm Damage','h1':'Give a damaged boundary a sensible next step.','label':'Fence repairs','category':'Services','description':'Explore fence repairs in Merseyside, including damaged panels, leaning posts and storm damage. Learn when a repair or replacement may be appropriate.','intro':'A loose panel, a leaning post or storm damage calls for a careful assessment. A targeted repair may be possible when the surrounding structure remains sound.','sections':[
('Keep clear of unstable sections','Do not lean on a damaged fence or allow children and pets near a section that may fall. Avoid trying to lift or straighten heavy panels under load. Photograph the issue from a safe position and note whether adjacent posts or panels are moving. If damage affects a public path or access route, explain that when arranging an assessment.'),
('Look beyond the broken panel','A panel can fail because its boards or frame are damaged, but the underlying cause may also involve posts, fixings or ground movement. Buried timber can deteriorate without the problem being visible above ground. A replacement panel on a failing support may not solve the issue. The repair decision should consider the neighbouring sections as well as the obvious damage.'),
('Repair or replace?','A local repair is often worth considering when only one section is affected and the remaining structure is suitable. More widespread decay, repeated storm movement or several failing posts can make a larger replacement more practical. Matching older panels exactly may not be possible. Discuss the appearance, expected scope and condition of retained sections before agreeing work.'),
('What to include in your enquiry','Give your town, the approximate number of affected panels and a description of the damage. Mention access restrictions, nearby walls and any gate attached to the damaged section. Do not assume emergency availability or a fixed repair price before the project has been reviewed. Our enquiry form provides a straightforward way to describe the issue and request the next conversation.')], 'related':['fencing-installation','timber-fencing','garden-gates']},
{'slug':'garden-gates','title':'Garden Gates Merseyside | Timber Side & Pedestrian Gates','h1':'The finishing touch that works every day.','label':'Garden gates','category':'Services','description':'Plan a timber garden or side gate in Merseyside. Consider opening width, posts, hinges, latches, access and a finish that complements the fence.','intro':'A garden gate should feel like part of the boundary, while opening smoothly and fitting the way you use the space. Small details make a large difference.','sections':[
('Measure the opening and the approach','The clear opening width, changes in ground level and direction of swing all matter. Think about bringing bins, bicycles or garden equipment through the gate. A path that slopes across the opening can affect clearance, and a gate should not obstruct a shared access route. Final measurements need to account for posts, hinges and required gaps.'),
('Support the weight properly','Gate posts carry different loads from ordinary intermediate fence posts. Timber species, board layout, bracing and hardware affect the gate’s weight and movement. Hinges and fixings should be suitable for the gate and support structure. A gate fixed to a weak existing post may make a boundary problem worse, so include the surrounding fence in the assessment.'),
('Choose practical hardware','Latch type, handle position and access from each side should suit the household. If security is a priority, discuss the complete arrangement rather than assuming a lock alone makes the boundary secure. Consider safe use around children and pets, and explain whether the gate serves a shared passage. Hardware exposed to coastal conditions may need particular care.'),
('Match the gate to the garden','Vertical boarding can complement closeboard fencing, while other profiles offer a lighter appearance. Ask about finishing treatment and care requirements, particularly at cut ends and joints. The gate image on this website is an illustrative design, not a completed project. Tell us your town, opening width and preferred style through the enquiry form to start planning a suitable specification.')], 'related':['timber-fencing','fence-repairs','fencing-installation']},
{'slug':'fencing-costs','title':'Fencing Costs Merseyside | How to Compare Quotations','h1':'Know what is in the quote.','label':'Fencing cost guide','category':'Advice','description':'Understand what affects fencing costs in Merseyside. Compare fence length, materials, posts, access, removal, gates and the scope of written quotations.','intro':'A useful fencing price is attached to a clear specification. Compare what is included, rather than treating every price per panel as the same job.','sections':[
('The main factors behind a quotation','Length and height set the scale of the boundary, but they do not tell the whole story. Material choice, post type, rails, gravel boards, gate hardware and decorative details affect the specification. Removal of an old fence and handling the waste add work. Restricted access, roots, hard surfaces and changes in level can also influence the labour involved.'),
('Ask for an itemised scope','Request the proposed fence dimensions and material range in writing. Confirm the number and type of posts, whether gravel boards are included and how gates are specified. Establish who removes and disposes of the old materials. Ask whether VAT applies and whether it is included. Quotes that describe these details are easier to compare fairly than a single headline amount.'),
('Allow for uncertainty responsibly','The condition of buried posts, underground obstructions or hidden services may not be clear from a photograph. Ask how additional work would be identified, priced and approved. Avoid agreeing open-ended extras without understanding the process. A site assessment can reduce uncertainty, although it cannot make every hidden condition visible before work begins.'),
('Payment and choosing a contractor','Understand any deposit, payment stages and cancellation terms before accepting a quote. Check claims about insurance, relevant experience and guarantees directly. The lowest figure may cover a different specification, while a higher figure does not itself prove quality. No fixed prices or unverified guarantees are advertised here. Share your project through the enquiry form to establish the information needed for a meaningful quote.')], 'related':['fencing-installation','timber-fencing','boundary-guide']},
{'slug':'boundary-guide','title':'Garden Fence Boundaries & Planning | Merseyside Guide','h1':'A little checking before the first post.','label':'Boundary & planning guide','category':'Advice','description':'Practical boundary and planning questions before a Merseyside fencing project. Check ownership, neighbours, height, highway proximity and local restrictions.','intro':'Before choosing a fence, make sure the proposed position and height are appropriate. A few early checks can prevent a much more difficult conversation later.','sections':[
('A fence is not necessarily the legal boundary','Do not assume ownership from the direction of the boards, posts or a neighbouring fence. Property documents can help, but title plans commonly show general rather than exact boundaries. If responsibility or position is uncertain, discuss it with the affected owner and seek appropriate professional advice. A fencing quotation does not resolve a legal boundary dispute.'),
('Check permission and property restrictions','In England, the usual permitted development limits for fences are subject to exceptions and conditions. Highway proximity, listed buildings, conservation matters and local directions can change what is allowed. Check the current Planning Portal guidance and your council’s advice for the actual property. This page is general project guidance, not a planning determination or legal opinion.'),
('Talk about the details with neighbours','Explain the proposed height, position, finish and timing before materials are ordered. Consider the appearance from both sides and any shared paths or access arrangements. Do not remove a neighbour’s fence, hedge or attachment without the necessary agreement. Existing planting, drainage and retaining structures should be considered as part of the plan.'),
('Prepare a useful enquiry','Include the town, approximate boundary length and whether the position has been agreed. Note public footpaths, adjacent roads, changes in level and any permissions already obtained. You do not need to share sensitive property documents through a simple enquiry form. If a legal or planning question remains unresolved, settle it before authorising the installation.')], 'related':['fencing-installation','garden-gates','fencing-costs']},
]

AREAS = [
('liverpool','Liverpool','Liverpool, Allerton, Aigburth, Childwall, Woolton, Wavertree and West Derby','From compact terraced gardens to larger suburban boundaries, Liverpool fencing projects benefit from a clear plan for access, screening and the existing site.','Access in a city garden','Some Liverpool homes have narrow side passages or access through the house. Tell us how materials can reach the rear garden and whether parking or deliveries need particular arrangements. A limited route can affect panel size, handling and the order of work. Protecting paths, planting and shared passages should be part of the conversation.','Privacy without crowding the space','In smaller gardens, a solid boundary can provide privacy but also influence light and the feeling of enclosure. Compare height, finish and planting together. An open trellis detail changes screening, so consider sightlines from neighbouring windows and paths rather than choosing on appearance alone.'),
('wirral','Wirral','Birkenhead, Wallasey, Bebington, Heswall, West Kirby, Hoylake, Moreton and surrounding Wirral neighbourhoods','Wirral gardens range from sheltered courtyards to more exposed coastal properties. Match the fencing specification to the conditions at the actual boundary.','Consider coastal exposure','Parts of the Wirral peninsula are exposed to strong winds and salt-laden air. A fence’s posts, fixings, foundations and panel design need to be considered together. Mention an exposed position or a history of storm movement when you enquire. Coastal proximity does not mean every property needs the same fence.','Levels, planting and established gardens','Older planting and changes in ground level can affect the line of a new boundary. Mature roots, retaining features and nearby drainage need care during planning. Explain which planting should be protected and how access works. A stepped panel layout may look different from a site-built fence, so discuss the finished appearance before agreeing a specification.'),
('sefton','Sefton','Bootle, Crosby, Waterloo, Formby, Maghull and Southport','From Bootle and Crosby to Formby and Southport, Sefton fencing projects should take account of garden layout, ground conditions and exposure.','From coast to inland gardens','Coastal and inland sites can have very different wind exposure. A solid fence can catch gusts, and adding height changes the loading on its supports. Ask how the proposed design suits the property rather than assuming a decorative or heavy panel is automatically stronger. Existing movement is useful information for the assessment.','Access, ground and neighbouring boundaries','Some Sefton gardens have established trees, uneven levels or limited side access. Soil conditions vary locally and should be assessed at the property. Include the old fence’s condition, nearby planting and whether you need a gate. Check boundary responsibility and any restrictions before arranging removal or replacement.'),
('knowsley','Knowsley','Huyton, Kirkby, Prescot, Halewood and Whiston','A well-planned boundary in Knowsley starts with your garden’s measurements, the condition of the existing fence and the privacy you need.','Plan a consistent boundary','Longer garden runs make alignment, post spacing and changes in level particularly noticeable. Compare stepped panels with other construction approaches where the ground slopes. If the new fence joins an existing wall or retained section, discuss the connection and the difference in appearance. Final dimensions should be confirmed at the site.','Practical access and everyday use','Side passages, shared routes and garden gates can all affect the design. Think about moving bins and equipment as well as screening views. Include children, pets and access needs in the brief without assuming a single style guarantees security. A gate and its supporting posts should be assessed as part of the whole boundary.'),
('st-helens','St Helens','St Helens, Eccleston, Rainhill, Billinge, Newton-le-Willows and Haydock','For St Helens borough gardens, focus on a fencing plan that suits the ground, the boundary length and the way the outdoor space is used.','Slopes and changes in level','Some properties have gardens that rise or fall along the boundary. Panel layout, gaps below the fence and the finished height need to be discussed together. Fencing should not be assumed to retain soil: retaining structures require their own assessment. Mention walls, banks and significant level differences in your enquiry.','Replace only what needs replacing','A localised damaged section may be suitable for repair if the remaining posts and boards are sound. Where decay or movement affects several sections, a broader replacement may make more sense. Matching older fencing can be difficult, so discuss the finish and condition of retained parts before deciding on the scope.')
]

for slug, name, towns, intro, h2a, pa, h2b, pb in AREAS:
    PAGES.append({'slug':'areas/'+slug,'title':f'Fencing {name} | Garden Fences, Repairs & Gates','h1':f'Thoughtful fencing for {name} gardens.','label':f'Fencing in {name}','category':'Merseyside areas','description':f'Plan fencing in {name}: garden fence installation, timber options, repairs and gates. Local project advice and enquiries across {name}.','intro':intro,'sections':[(h2a,pa),(h2b,pb),(f'Enquiries across {name}',f'Project enquiries can include {towns}. Use your town and postcode area to describe the location; do not assume a listing guarantees a particular appointment or project availability. Share approximate length, desired height, material preferences and whether the old fence needs removing. Photos can support a discussion, with final measurements and site conditions confirmed before work is agreed.'),('Choose a clear specification','Whether you are looking at timber panels, closeboard, composite fencing or a new gate, compare the complete specification. Posts, fixings, ground preparation, access and waste handling matter as well as the visible fence. Check ownership and planning restrictions before authorising work. Our fencing guides explain the options and the enquiry form helps bring your project information together.')],'related':['fencing-installation','fence-repairs','timber-fencing','areas']})
